# Generated by Django 4.2.7 on 2023-11-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "my_field_name",
                    models.CharField(
                        help_text="Enter field documentation", max_length=20
                    ),
                ),
            ],
        ),
    ]
