# Generated by Django 4.2.7 on 2023-11-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_organisationevent_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationevent',
            name='category',
        ),
        migrations.AddField(
            model_name='organisationevent',
            name='category',
            field=models.ManyToManyField(help_text='Select category for this event', to='management.category'),
        ),
    ]
