# Generated by Django 4.2.7 on 2023-11-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_organisationevent_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationevent',
            name='category',
        ),
        migrations.AddField(
            model_name='organisationevent',
            name='category',
            field=models.ForeignKey(help_text='Select category for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.category'),
        ),
    ]
