# Generated by Django 4.2.7 on 2023-11-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationevent',
            name='registered_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
